### ISSUE TITLE
How to register properly and correctly

### ISSUE THREAD

**Issue by sigit-khoirun-nizam** [aliatayee/Attendance_Management_System#4]
Assalamualaikum, at first I changed the route url with true but the error is like this, is there a solution, thank you
![Screenshot from 2022-07-03 17-45-58](https://user-images.githubusercontent.com/57288412/177036079-2c69c1c7-dd5d-4f26-8557-e13afeb75006.png)
route :
![Screenshot from 2022-07-03 17-47-02](https://user-images.githubusercontent.com/57288412/177036118-a2dfbb79-624b-4a13-9f27-5b63f028da59.png)

**Comment by aliatayee** [comment]
Hello @sigit-khoirun-nizam,
Thank you for writing the issue. It seems you did not insert the user and role correctly that is why you are getting this error. I have updated the user seeder please pull it once again and run ```php artisan db:seed``` it will set the user and role with the following credential : 
email: admin@ams.com
password: admin@ams.com
https://github.com/aliatayee/Attendance_Management_System/blob/1de125b844074b4d6cbb29573d8795092c6dd0d9/database/seeders/DatabaseSeeder.php#L18-L31

If there was any issue let me know.

**Comment by sigit-khoirun-nizam** [comment]
Alhamdulillah, now the problem is gone, thank you
