### ISSUE TITLE
I am facing an issue

### ISSUE THREAD

**Issue by dev21wp** [aliatayee/Attendance_Management_System#5]
Assalam o Alikum  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (Admin, admin@ams.com, $2y$10$4A.8uZbRJ9qu1FWPKFZ0qOgVXOPEuNtHzp2491P9WUuaUSCZ7QfXC, 2022-08-19 11:40:16, 2022-08-19 11:40:16))

**Comment by mango2001** [comment]
**Solution:**
Go to config/database.php, look for this 'port' => env('DB_PORT', '3306'),
then you take the port number then you copy paste in your .env file DB_PORT=3306

**Comment by dev21wp** [comment]
Thank you Soo Much Issue Resolved
